const cards = [
  {
    NumericalValue: 1,
    Suit: "Hearts",
    Value: "Ace",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 2,
    Suit: "Hearts",
    Value: "2",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 3,
    Suit: "Hearts",
    Value: "3",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 4,
    Suit: "Hearts",
    Value: "4",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 5,
    Suit: "Hearts",
    Value: "5",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 6,
    Suit: "Hearts",
    Value: "6",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 7,
    Suit: "Hearts",
    Value: "7",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 8,
    Suit: "Hearts",
    Value: "8",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 9,
    Suit: "Hearts",
    Value: "9",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 10,
    Suit: "Hearts",
    Value: "10",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 11,
    Suit: "Hearts",
    Value: "Jack",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 12,
    Suit: "Hearts",
    Value: "Queen",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 13,
    Suit: "Hearts",
    Value: "King",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 1,
    Suit: "Diamonds",
    Value: "Ace",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 2,
    Suit: "Diamonds",
    Value: "2",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 3,
    Suit: "Diamonds",
    Value: "3",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 4,
    Suit: "Diamonds",
    Value: "4",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 5,
    Suit: "Diamonds",
    Value: "5",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 6,
    Suit: "Diamonds",
    Value: "6",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 7,
    Suit: "Diamonds",
    Value: "7",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 8,
    Suit: "Diamonds",
    Value: "8",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 9,
    Suit: "Diamonds",
    Value: "9",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 10,
    Suit: "Diamonds",
    Value: "10",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 11,
    Suit: "Diamonds",
    Value: "Jack",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 12,
    Suit: "Diamonds",
    Value: "Queen",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 13,
    Suit: "Diamonds",
    Value: "King",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 1,
    Suit: "Clubs",
    Value: "Ace",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 2,
    Suit: "Clubs",
    Value: "2",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 3,
    Suit: "Clubs",
    Value: "3",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 4,
    Suit: "Clubs",
    Value: "4",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 5,
    Suit: "Clubs",
    Value: "5",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 6,
    Suit: "Clubs",
    Value: "6",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 7,
    Suit: "Clubs",
    Value: "7",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 8,
    Suit: "Clubs",
    Value: "8",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 9,
    Suit: "Clubs",
    Value: "9",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 10,
    Suit: "Clubs",
    Value: "10",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 11,
    Suit: "Clubs",
    Value: "Jack",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 12,
    Suit: "Clubs",
    Value: "Queen",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 13,
    Suit: "Clubs",
    Value: "King",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 1,
    Suit: "Spades",
    Value: "Ace",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 2,
    Suit: "Spades",
    Value: "2",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 3,
    Suit: "Spades",
    Value: "3",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 4,
    Suit: "Spades",
    Value: "4",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 5,
    Suit: "Spades",
    Value: "5",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 6,
    Suit: "Spades",
    Value: "6",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 7,
    Suit: "Spades",
    Value: "7",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 8,
    Suit: "Spades",
    Value: "8",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 9,
    Suit: "Spades",
    Value: "9",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 10,
    Suit: "Spades",
    Value: "10",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 11,
    Suit: "Spades",
    Value: "Jack",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 12,
    Suit: "Spades",
    Value: "Queen",
    Flipped: false,
    Correct: false,
  },
  {
    NumericalValue: 13,
    Suit: "Spades",
    Value: "King",
    Flipped: false,
    Correct: false,
  },
];
export { cards };
